# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    # TODO: This currently fails with "command not found"
    skip: [terraform_fmt, terraform_validate]

repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
            exclude_types: [markdown]
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.72.1
      hooks:
          - id: terraform_fmt
          - id: terraform_validate
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.18.0
      hooks:
          - id: eslint
            files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
            types: [file]
            additional_dependencies:
                - eslint@8.17.0
                - typescript@4.7.3
                - '@typescript-eslint/eslint-plugin@5.28.0'
                - '@typescript-eslint/parser@5.28.0'
                - eslint-config-prettier@8.5.0
                - eslint-plugin-jest@26.5.3
                - eslint-plugin-vue@9.1.1
                - vue-eslint-parser@9.0.2
                - jest@28.1.1
